# Version: $Id: Makefile.pic 1276 2013-05-12 21:14:09Z ag0015 $

OBJ = xor_checksum.o get_ba_address.o # idle_packet.o reset_packet.o # these last 2 do not compile with PIC!

include ../../../lib/pattern.$(ARCH)

